[project]
name = 'med'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.med]
path = 'contracts/med.clar'
clarity_version = 3
epoch = 3.1
[contracts.medical-alerts]
path = 'contracts/medical-alerts.clar'
clarity_version = 3
epoch = 3.1
[contracts.interhospital-sharing]
path = 'contracts/interhospital-sharing.clar'
clarity_version = 3
epoch = 3.1
[contracts.medical-ai-integration]
path = 'contracts/medical-ai-integration.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
